// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	membership_products "gym-membership/business/membership_products"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// DeleteByID provides a mock function with given fields: id
func (_m *Repository) DeleteByID(id uint) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: offset, limit
func (_m *Repository) GetAll(offset int, limit int) ([]membership_products.Domain, int64, error) {
	ret := _m.Called(offset, limit)

	var r0 []membership_products.Domain
	if rf, ok := ret.Get(0).(func(int, int) []membership_products.Domain); ok {
		r0 = rf(offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]membership_products.Domain)
		}
	}

	var r1 int64
	if rf, ok := ret.Get(1).(func(int, int) int64); ok {
		r1 = rf(offset, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(int, int) error); ok {
		r2 = rf(offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetByID provides a mock function with given fields: id
func (_m *Repository) GetByID(id uint) (membership_products.Domain, error) {
	ret := _m.Called(id)

	var r0 membership_products.Domain
	if rf, ok := ret.Get(0).(func(uint) membership_products.Domain); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(membership_products.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: newData
func (_m *Repository) Insert(newData *membership_products.Domain) (membership_products.Domain, error) {
	ret := _m.Called(newData)

	var r0 membership_products.Domain
	if rf, ok := ret.Get(0).(func(*membership_products.Domain) membership_products.Domain); ok {
		r0 = rf(newData)
	} else {
		r0 = ret.Get(0).(membership_products.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*membership_products.Domain) error); ok {
		r1 = rf(newData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateByID provides a mock function with given fields: id, newData
func (_m *Repository) UpdateByID(id uint, newData *membership_products.Domain) (membership_products.Domain, error) {
	ret := _m.Called(id, newData)

	var r0 membership_products.Domain
	if rf, ok := ret.Get(0).(func(uint, *membership_products.Domain) membership_products.Domain); ok {
		r0 = rf(id, newData)
	} else {
		r0 = ret.Get(0).(membership_products.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, *membership_products.Domain) error); ok {
		r1 = rf(id, newData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
