// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	trainers "gym-membership/business/trainers"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetAll provides a mock function with given fields:
func (_m *Repository) GetAll() ([]trainers.Domain, error) {
	ret := _m.Called()

	var r0 []trainers.Domain
	if rf, ok := ret.Get(0).(func() []trainers.Domain); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]trainers.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
