// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	members "gym-membership/business/members"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetByUserID provides a mock function with given fields: userID
func (_m *Repository) GetByUserID(userID uint) (members.Domain, error) {
	ret := _m.Called(userID)

	var r0 members.Domain
	if rf, ok := ret.Get(0).(func(uint) members.Domain); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(members.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: data
func (_m *Repository) Insert(data *members.Domain) error {
	ret := _m.Called(data)

	var r0 error
	if rf, ok := ret.Get(0).(func(*members.Domain) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
