// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	members "gym-membership/business/members"

	mock "github.com/stretchr/testify/mock"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// GetByUserID provides a mock function with given fields: userID
func (_m *Usecase) GetByUserID(userID uint) (members.Domain, error) {
	ret := _m.Called(userID)

	var r0 members.Domain
	if rf, ok := ret.Get(0).(func(uint) members.Domain); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(members.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
