// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	videos "gym-membership/business/videos"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetAll provides a mock function with given fields:
func (_m *Repository) GetAll() ([]videos.Domain, error) {
	ret := _m.Called()

	var r0 []videos.Domain
	if rf, ok := ret.Get(0).(func() []videos.Domain); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]videos.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetClassificationID provides a mock function with given fields: classification
func (_m *Repository) GetClassificationID(classification string) (int, error) {
	ret := _m.Called(classification)

	var r0 int
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(classification)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(classification)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: videoData
func (_m *Repository) Insert(videoData *videos.Domain) (videos.Domain, error) {
	ret := _m.Called(videoData)

	var r0 videos.Domain
	if rf, ok := ret.Get(0).(func(*videos.Domain) videos.Domain); ok {
		r0 = rf(videoData)
	} else {
		r0 = ret.Get(0).(videos.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*videos.Domain) error); ok {
		r1 = rf(videoData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateByID provides a mock function with given fields: id, videoData
func (_m *Repository) UpdateByID(id uint, videoData *videos.Domain) (videos.Domain, error) {
	ret := _m.Called(id, videoData)

	var r0 videos.Domain
	if rf, ok := ret.Get(0).(func(uint, *videos.Domain) videos.Domain); ok {
		r0 = rf(id, videoData)
	} else {
		r0 = ret.Get(0).(videos.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, *videos.Domain) error); ok {
		r1 = rf(id, videoData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
