// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	videos "gym-membership/business/videos"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: title, offset, limit
func (_m *Repository) GetAll(title string, offset int, limit int) ([]videos.Domain, int64, error) {
	ret := _m.Called(title, offset, limit)

	var r0 []videos.Domain
	if rf, ok := ret.Get(0).(func(string, int, int) []videos.Domain); ok {
		r0 = rf(title, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]videos.Domain)
		}
	}

	var r1 int64
	if rf, ok := ret.Get(1).(func(string, int, int) int64); ok {
		r1 = rf(title, offset, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string, int, int) error); ok {
		r2 = rf(title, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Insert provides a mock function with given fields: videoData
func (_m *Repository) Insert(videoData *videos.Domain) (videos.Domain, error) {
	ret := _m.Called(videoData)

	var r0 videos.Domain
	if rf, ok := ret.Get(0).(func(*videos.Domain) videos.Domain); ok {
		r0 = rf(videoData)
	} else {
		r0 = ret.Get(0).(videos.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*videos.Domain) error); ok {
		r1 = rf(videoData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateByID provides a mock function with given fields: id, videoData
func (_m *Repository) UpdateByID(id uint, videoData *videos.Domain) (videos.Domain, error) {
	ret := _m.Called(id, videoData)

	var r0 videos.Domain
	if rf, ok := ret.Get(0).(func(uint, *videos.Domain) videos.Domain); ok {
		r0 = rf(id, videoData)
	} else {
		r0 = ret.Get(0).(videos.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, *videos.Domain) error); ok {
		r1 = rf(id, videoData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
