// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	videos "gym-membership/business/videos"

	mock "github.com/stretchr/testify/mock"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: title, page
func (_m *Usecase) GetAll(title string, page int) ([]videos.Domain, error) {
	ret := _m.Called(title, page)

	var r0 []videos.Domain
	if rf, ok := ret.Get(0).(func(string, int) []videos.Domain); ok {
		r0 = rf(title, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]videos.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(title, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: videoData, adminID
func (_m *Usecase) Insert(videoData *videos.Domain, adminID uint) (string, error) {
	ret := _m.Called(videoData, adminID)

	var r0 string
	if rf, ok := ret.Get(0).(func(*videos.Domain, uint) string); ok {
		r0 = rf(videoData, adminID)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*videos.Domain, uint) error); ok {
		r1 = rf(videoData, adminID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateByID provides a mock function with given fields: id, videoData, adminID
func (_m *Usecase) UpdateByID(id uint, videoData *videos.Domain, adminID uint) (string, error) {
	ret := _m.Called(id, videoData, adminID)

	var r0 string
	if rf, ok := ret.Get(0).(func(uint, *videos.Domain, uint) string); ok {
		r0 = rf(id, videoData, adminID)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, *videos.Domain, uint) error); ok {
		r1 = rf(id, videoData, adminID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
