// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	videos "gym-membership/business/videos"

	mock "github.com/stretchr/testify/mock"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// DeleteByID provides a mock function with given fields: id
func (_m *Usecase) DeleteByID(id uint) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: title, page
func (_m *Usecase) GetAll(title string, page int) ([]videos.Domain, int, int, int64, error) {
	ret := _m.Called(title, page)

	var r0 []videos.Domain
	if rf, ok := ret.Get(0).(func(string, int) []videos.Domain); ok {
		r0 = rf(title, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]videos.Domain)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(string, int) int); ok {
		r1 = rf(title, page)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 int
	if rf, ok := ret.Get(2).(func(string, int) int); ok {
		r2 = rf(title, page)
	} else {
		r2 = ret.Get(2).(int)
	}

	var r3 int64
	if rf, ok := ret.Get(3).(func(string, int) int64); ok {
		r3 = rf(title, page)
	} else {
		r3 = ret.Get(3).(int64)
	}

	var r4 error
	if rf, ok := ret.Get(4).(func(string, int) error); ok {
		r4 = rf(title, page)
	} else {
		r4 = ret.Error(4)
	}

	return r0, r1, r2, r3, r4
}

// Insert provides a mock function with given fields: videoData
func (_m *Usecase) Insert(videoData *videos.Domain) (string, error) {
	ret := _m.Called(videoData)

	var r0 string
	if rf, ok := ret.Get(0).(func(*videos.Domain) string); ok {
		r0 = rf(videoData)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*videos.Domain) error); ok {
		r1 = rf(videoData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateByID provides a mock function with given fields: id, videoData
func (_m *Usecase) UpdateByID(id uint, videoData *videos.Domain) (string, error) {
	ret := _m.Called(id, videoData)

	var r0 string
	if rf, ok := ret.Get(0).(func(uint, *videos.Domain) string); ok {
		r0 = rf(id, videoData)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, *videos.Domain) error); ok {
		r1 = rf(id, videoData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
