// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	class "gym-membership/business/class"

	mock "github.com/stretchr/testify/mock"

	transactionClass "gym-membership/business/transactionClass"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetActiveClass provides a mock function with given fields: idUser
func (_m *Repository) GetActiveClass(idUser uint) ([]class.Domain, error) {
	ret := _m.Called(idUser)

	var r0 []class.Domain
	if rf, ok := ret.Get(0).(func(uint) []class.Domain); ok {
		r0 = rf(idUser)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]class.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(idUser)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: status, idUser, offset, limit
func (_m *Repository) GetAll(status string, idUser uint, offset int, limit int) ([]transactionClass.Domain, int64, error) {
	ret := _m.Called(status, idUser, offset, limit)

	var r0 []transactionClass.Domain
	if rf, ok := ret.Get(0).(func(string, uint, int, int) []transactionClass.Domain); ok {
		r0 = rf(status, idUser, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]transactionClass.Domain)
		}
	}

	var r1 int64
	if rf, ok := ret.Get(1).(func(string, uint, int, int) int64); ok {
		r1 = rf(status, idUser, offset, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string, uint, int, int) error); ok {
		r2 = rf(status, idUser, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Insert provides a mock function with given fields: transactionClassData
func (_m *Repository) Insert(transactionClassData *transactionClass.Domain) (transactionClass.Domain, error) {
	ret := _m.Called(transactionClassData)

	var r0 transactionClass.Domain
	if rf, ok := ret.Get(0).(func(*transactionClass.Domain) transactionClass.Domain); ok {
		r0 = rf(transactionClassData)
	} else {
		r0 = ret.Get(0).(transactionClass.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*transactionClass.Domain) error); ok {
		r1 = rf(transactionClassData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatus provides a mock function with given fields: idTransactionClass, idAdmin, status
func (_m *Repository) UpdateStatus(idTransactionClass uint, idAdmin uint, status string) (transactionClass.Domain, error) {
	ret := _m.Called(idTransactionClass, idAdmin, status)

	var r0 transactionClass.Domain
	if rf, ok := ret.Get(0).(func(uint, uint, string) transactionClass.Domain); ok {
		r0 = rf(idTransactionClass, idAdmin, status)
	} else {
		r0 = ret.Get(0).(transactionClass.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, uint, string) error); ok {
		r1 = rf(idTransactionClass, idAdmin, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
