// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	class "gym-membership/business/class"

	mock "github.com/stretchr/testify/mock"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: title, page
func (_m *Usecase) GetAll(title string, page int) ([]class.Domain, int, int, int64, error) {
	ret := _m.Called(title, page)

	var r0 []class.Domain
	if rf, ok := ret.Get(0).(func(string, int) []class.Domain); ok {
		r0 = rf(title, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]class.Domain)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(string, int) int); ok {
		r1 = rf(title, page)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 int
	if rf, ok := ret.Get(2).(func(string, int) int); ok {
		r2 = rf(title, page)
	} else {
		r2 = ret.Get(2).(int)
	}

	var r3 int64
	if rf, ok := ret.Get(3).(func(string, int) int64); ok {
		r3 = rf(title, page)
	} else {
		r3 = ret.Get(3).(int64)
	}

	var r4 error
	if rf, ok := ret.Get(4).(func(string, int) error); ok {
		r4 = rf(title, page)
	} else {
		r4 = ret.Error(4)
	}

	return r0, r1, r2, r3, r4
}

// Insert provides a mock function with given fields: classData
func (_m *Usecase) Insert(classData *class.Domain) (string, error) {
	ret := _m.Called(classData)

	var r0 string
	if rf, ok := ret.Get(0).(func(*class.Domain) string); ok {
		r0 = rf(classData)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*class.Domain) error); ok {
		r1 = rf(classData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ScheduleByID provides a mock function with given fields: id
func (_m *Usecase) ScheduleByID(id uint) ([]class.Domain, error) {
	ret := _m.Called(id)

	var r0 []class.Domain
	if rf, ok := ret.Get(0).(func(uint) []class.Domain); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]class.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateClassByID provides a mock function with given fields: id, articleData
func (_m *Usecase) UpdateClassByID(id uint, articleData *class.Domain) (string, error) {
	ret := _m.Called(id, articleData)

	var r0 string
	if rf, ok := ret.Get(0).(func(uint, *class.Domain) string); ok {
		r0 = rf(id, articleData)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, *class.Domain) error); ok {
		r1 = rf(id, articleData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateParticipant provides a mock function with given fields: idClass
func (_m *Usecase) UpdateParticipant(idClass int) (string, error) {
	ret := _m.Called(idClass)

	var r0 string
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(idClass)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(idClass)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
